---

# forksTunnelContextTunnelIdentifier
# forksTunnelContextSourceHostname
# forksTunnelContextSourceSystemUsername
# forksTunnelContextSourceHomeDirectory
# forksTunnelContextTargetHostname
# forksTunnelContextTunnelPorts



- name: Prepare Forks Tunnel
  include_tasks: prepare.yml


...

