---


# forksTunnelContextTunnelIdentifier
# forksTunnelContextSourceHostname
# forksTunnelContextSourceSystemUsername
# forksTunnelContextSourceHomeDirectory
# forksTunnelContextTargetHostname
# forksTunnelContextTunnelPorts


- name: Stop Forks Tunnel
  when:
    - forksTunnelContextTunnelState == 'stopped'
    - inventory_hostname == forksTunnelContextSourceHostname
  include_tasks: stop.yml


- name: Prepare Forks Tunnel
  when: forksTunnelContextTunnelState != 'stopped'
  include_tasks: prepare.yml

- name: Start Forks Tunnel
  when:
    - forksTunnelContextTunnelState != 'stopped'
    - inventory_hostname == forksTunnelContextSourceHostname
  include_tasks: tunnel.yml


...
