---


  # HINT: Exists-Check of module below failing ocassionally
  # RESULT: exists: tunnelTargetUserExistsCommandResult.rc == 0
- name: Check if tunnel system user exists on target host
  delegate_to: "{{ forksTunnelContextTargetHostname }}"
  command: "id -u {{ forksTunnelTargetUsername }}"
  register: tunnelTargetUserExistsCommandResult

- name: Create Forks tunnel system user on target host
  when: tunnelTargetUserExistsCommandResult.rc != 0
  delegate_to: "{{ forksTunnelContextTargetHostname }}"
  become: true
  user:
    name: "{{ forksTunnelTargetUsername }}"
    home: "{{ forksTunnelTargetHomeDirectory }}"
    shell: /sbin/nologin
    comment: Forks Tunnel Endpoint
    umask: '0077'
  run_once: true

  # Due to ansible warning
- name: Create remote temp dir for ansible
  delegate_to: "{{ forksTunnelContextTargetHostname }}"
  become: true
  file:
    path: "{{ forksTunnelTargetHomeDirectory }}/.ansible/tmp"
    state: directory
    owner: "{{ forksTunnelTargetUsername }}"
    group: "{{ forksTunnelTargetUsername }}"
    mode: 0750


...
